# Static configuration for Traefik
api:
  dashboard: true
  debug: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      middlewares:
        - my-crowdsec-bouncer-traefik-plugin@file
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    # trust Cloudflare's X-Forwarded-* headers
    # This prevents our logs from resolving to these addresses,
    # and will instead show the actual end-user's IP address
    forwardedHeaders:
      trustedIPs:
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/12
        - 172.64.0.0/13
        - 131.0.72.0/22
    http:
      middlewares:
        - my-crowdsec-bouncer-traefik-plugin@file
      tls:
        # options: foobar
        certResolver: cloudflare
        domains:
          - main: ${BLOG_DOMAIN}
            sans:
              - "*.${BLOG_DOMAIN}"

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
  file:
    filename: "traefik-sites.yml"
    watch: true
  providersThrottleDuration: 10

log:
  filePath: /logs/traefik.log

accessLog:
  filePath: /logs/access.log
  bufferingSize: 100

experimental:
  plugins:
    crowdsec-bouncer-traefik-plugin:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: ${BOUNCER_VERSION}

certificatesResolvers:
  cloudflare:
    acme:
      email: ${ACME_EMAIL}
      storage: /acme/acme.json
      # comment this out once it works... and delete any certs you got
      # caserver: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

